// <auto-generated />
using System;
using MassPersona.RazorPageApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MassPersona.RazorPageApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241003204011_second_seed")]
    partial class second_seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassPersona.RazorPageApp.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ReviewID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Category");

                    b.Property<DateTime>("DateReviewed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateReviewed");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("Rating");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ReviewText");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Title");

                    b.HasKey("ReviewID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            Category = "Movie",
                            DateReviewed = new DateTime(2024, 10, 3, 20, 40, 10, 920, DateTimeKind.Utc).AddTicks(3404),
                            Rating = 4,
                            ReviewText = "I enjoyed it more than the first one.",
                            Title = "Dune 2"
                        },
                        new
                        {
                            ReviewID = 2,
                            Category = "Game",
                            DateReviewed = new DateTime(2024, 10, 3, 20, 40, 10, 920, DateTimeKind.Utc).AddTicks(3408),
                            Rating = 4,
                            ReviewText = "Brough back nostalgia as I played it when it first came out.",
                            Title = "Warcraft Classic"
                        },
                        new
                        {
                            ReviewID = 3,
                            Category = "Book",
                            DateReviewed = new DateTime(2024, 10, 3, 20, 40, 10, 920, DateTimeKind.Utc).AddTicks(3409),
                            Rating = 2,
                            ReviewText = "A little difficult to understand, but paked my interest to create Microservice solutions. For example https://github.com/ponssong/EShopMicSer",
                            Title = ".NET Microservices: Architecture for containerized .NET Applications"
                        },
                        new
                        {
                            ReviewID = 4,
                            Category = "Show",
                            DateReviewed = new DateTime(2024, 10, 3, 20, 40, 10, 920, DateTimeKind.Utc).AddTicks(3411),
                            Rating = 3,
                            ReviewText = "I enjoyed the first so i will continue to watch.",
                            Title = "Rings of Power"
                        },
                        new
                        {
                            ReviewID = 5,
                            Category = "Show",
                            DateReviewed = new DateTime(2024, 10, 3, 20, 40, 10, 920, DateTimeKind.Utc).AddTicks(3413),
                            Rating = 4,
                            ReviewText = "I read the manhua. So I wanted to see the anime.",
                            Title = "Solo Leveling"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
